/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package robledo_Pos;

import robledo_Pos.GreenWich_POS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roble
 */
public class Receipt12 extends javax.swing.JFrame {

    /**
     * Creates new form User_Log_In
     */
    public Receipt12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReceiptTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ReceiptChangeField = new javax.swing.JTextField();
        Change = new javax.swing.JLabel();
        AmountPaid = new javax.swing.JLabel();
        TransactionType = new javax.swing.JLabel();
        ContactNum = new javax.swing.JLabel();
        TransactionNum = new javax.swing.JLabel();
        CustomerName2 = new javax.swing.JLabel();
        OverLoadCardNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OrderTotalAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReceiptTable.setBackground(new java.awt.Color(51, 51, 51));
        ReceiptTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ReceiptTable.setForeground(new java.awt.Color(255, 255, 255));
        ReceiptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(ReceiptTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 470, 190));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 120, 30));

        ReceiptChangeField.setBackground(new java.awt.Color(51, 51, 51));
        ReceiptChangeField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ReceiptChangeField.setForeground(new java.awt.Color(255, 255, 255));
        ReceiptChangeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ReceiptChangeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 190, 30));

        Change.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        Change.setForeground(new java.awt.Color(255, 255, 255));
        Change.setText("CHANGE");
        getContentPane().add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 80, 30));

        AmountPaid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AmountPaid.setForeground(new java.awt.Color(255, 255, 255));
        AmountPaid.setText("AMOUNT PAID :");
        getContentPane().add(AmountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 310, 30));

        TransactionType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TransactionType.setForeground(new java.awt.Color(255, 255, 255));
        TransactionType.setText("Transaction Type :");
        getContentPane().add(TransactionType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 430, 20));

        ContactNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContactNum.setForeground(new java.awt.Color(255, 255, 255));
        ContactNum.setText("Contact Number :");
        getContentPane().add(ContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 430, 20));

        TransactionNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TransactionNum.setForeground(new java.awt.Color(255, 255, 255));
        TransactionNum.setText("Transaction Number:");
        getContentPane().add(TransactionNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 430, 20));

        CustomerName2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CustomerName2.setForeground(new java.awt.Color(255, 255, 255));
        CustomerName2.setText("Customer Name:");
        getContentPane().add(CustomerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 20));

        OverLoadCardNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OverLoadCardNum.setForeground(new java.awt.Color(255, 255, 255));
        OverLoadCardNum.setText("OverloadCard Number:");
        getContentPane().add(OverLoadCardNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 430, 20));

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 247, 247));
        jLabel8.setText("RECEIPT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 200, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/My project-1 (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 340, 80));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blackradiant - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 80));

        OrderTotalAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OrderTotalAmount.setForeground(new java.awt.Color(255, 255, 255));
        OrderTotalAmount.setText("TOTAL AMOUNT :");
        getContentPane().add(OrderTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 340, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ReceiptBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 510, 480));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blackradiant - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 510, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GreenWich_POS pos = new GreenWich_POS();
        DefaultTableModel model = (DefaultTableModel) GreenWich_POS.model;
        GreenWich_POS.CustomerName.setText(User_Registration.firstName + " " + User_Registration.lastname);
        GreenWich_POS.TransactionMode = pos.TransactionMode;
        GreenWich_POS.totalAmount = pos.totalAmount;
        GreenWich_POS.CustomerName.setText(User_Registration.firstName + " " + User_Registration.lastname);
        GreenWich_POS.CardLabTxt.setText(pos.cardLabTxt);
        GreenWich_POS.TotalTxt.setText(GreenWich_POS.ToTalToReceipt);
        GreenWich_POS.myTable.setModel(model);

        pos.show();
        show(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel AmountPaid;
    public static javax.swing.JLabel Change;
    public static javax.swing.JLabel ContactNum;
    public static javax.swing.JLabel CustomerName2;
    public static javax.swing.JLabel OrderTotalAmount;
    public static javax.swing.JLabel OverLoadCardNum;
    public static javax.swing.JTextField ReceiptChangeField;
    public static javax.swing.JTable ReceiptTable;
    public static javax.swing.JLabel TransactionNum;
    public static javax.swing.JLabel TransactionType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
