/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacPac;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author roble
 */
public class NewCLass extends javax.swing.JFrame {

    /**
     * Creates new form TicTac_Toe
     */
    public NewCLass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelXscore = new javax.swing.JLabel();
        jLabelOscore = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setForeground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PLAYER X");

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("TIC TAC TOE");

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("PLAYER O");

        jLabelXscore.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelXscore.setForeground(new java.awt.Color(0, 0, 255));
        jLabelXscore.setText("0");

        jLabelOscore.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelOscore.setForeground(new java.awt.Color(255, 153, 0));
        jLabelOscore.setText("0");

        jPanel1.setForeground(new java.awt.Color(204, 255, 102));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton3.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton4.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton9.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jButton7.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 0, 0));
        jButton10.setText("New Game");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelXscore, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOscore, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXscore)
                    .addComponent(jLabelOscore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton1.setText(Player);
        player_turn();
        jButton1.setEnabled(false);
        check_winner();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton2.setText(Player);
        player_turn();
        jButton2.setEnabled(false);
        check_winner();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton3.setText(Player);
        player_turn();
        jButton3.setEnabled(false);
        check_winner();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton4.setText(Player);
        player_turn();
        jButton4.setEnabled(false);
        check_winner();
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton5.setText(Player);
        player_turn();
        jButton5.setEnabled(false);
        check_winner();
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton6.setText(Player);
        player_turn();
        jButton6.setEnabled(false);
        check_winner();
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton7.setText(Player);
        player_turn();
        jButton7.setEnabled(false);
        check_winner();
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton8.setText(Player);
        player_turn();
        jButton8.setEnabled(false);
        check_winner();
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButton9.setText(Player);
        player_turn();
        jButton9.setEnabled(false);
        check_winner();
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton5.setEnabled(true);
       jButton6.setEnabled(true);
       jButton7.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(true);
       
       jButton1.setText("");
       jButton2.setText("");
       jButton3.setText("");
       jButton4.setText("");
       jButton5.setText("");
       jButton6.setText("");
       jButton7.setText("");
       jButton8.setText("");
       jButton9.setText("");
       
       jButton1.setBackground(Color.lightGray);
       jButton2.setBackground(Color.lightGray);
       jButton3.setBackground(Color.lightGray);
       jButton4.setBackground(Color.lightGray);
       jButton5.setBackground(Color.lightGray);
       jButton6.setBackground(Color.lightGray);
       jButton7.setBackground(Color.lightGray);
       jButton8.setBackground(Color.lightGray);
       jButton9.setBackground(Color.lightGray);
       
       Player = "X";
    }                                         

    int Xscore = 0, Oscore = 0;
    private String Player = "X";

    void player_turn() {
        if (Player == "X") {
            Player = "O";
        } else {
            Player = "X";
        }
    }

    void win_button() {
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);

    }

    void score() {
        jLabelXscore.setText(Integer.toString(Xscore));
        jLabelOscore.setText(Integer.toString(Oscore));
    }

    void check_winner() {
        String b1 = jButton1.getText();
        String b2 = jButton2.getText();
        String b3 = jButton3.getText();
        String b4 = jButton4.getText();
        String b5 = jButton5.getText();
        String b6 = jButton6.getText();
        String b7 = jButton7.getText();
        String b8 = jButton8.getText();
        String b9 = jButton9.getText();
        //for Player X    
        if (b1 == "X" && b2 == "X" && b3 == "X") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton2.setBackground(Color.yellow);
            jButton3.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b4 == "X" && b5 == "X" && b6 == "X") {
            win_button();
            jButton4.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton6.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b7 == "X" && b8 == "X" && b9 == "X") {
            win_button();
            jButton7.setBackground(Color.yellow);
            jButton8.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b3 == "X" && b5 == "X" && b7 == "X") {
            win_button();
            jButton3.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton7.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b1 == "X" && b5 == "X" && b9 == "X") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b1 == "X" && b4 == "X" && b7 == "X") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton4.setBackground(Color.yellow);
            jButton7.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b2 == "X" && b5 == "X" && b8 == "X") {
            win_button();
            jButton2.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton8.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        if (b3 == "X" && b6 == "X" && b9 == "X") {
            win_button();
            jButton3.setBackground(Color.yellow);
            jButton6.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player X Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Xscore++;
            score();
        }
        //for Player O    
        if (b1 == "O" && b2 == "O" && b3 == "O") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton2.setBackground(Color.yellow);
            jButton3.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b4 == "O" && b5 == "O" && b6 == "O") {
            win_button();
            jButton4.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton6.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b7 == "O" && b8 == "O" && b9 == "O") {
            win_button();
            jButton7.setBackground(Color.yellow);
            jButton8.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b3 == "O" && b5 == "O" && b7 == "O") {
            win_button();
            jButton3.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton7.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b1 == "O" && b5 == "O" && b9 == "O") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b1 == "O" && b4 == "O" && b7 == "O") {
            win_button();
            jButton1.setBackground(Color.yellow);
            jButton4.setBackground(Color.yellow);
            jButton7.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b2 == "O" && b5 == "O" && b8 == "O") {
            win_button();
            jButton2.setBackground(Color.yellow);
            jButton5.setBackground(Color.yellow);
            jButton8.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
        if (b3 == "O" && b6 == "O" && b9 == "O") {
            win_button();
            jButton3.setBackground(Color.yellow);
            jButton6.setBackground(Color.yellow);
            jButton9.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(this, "Player O Wins", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            Oscore++;
            score();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac_Toe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac_Toe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelOscore;
    private javax.swing.JLabel jLabelXscore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration                   
}
